### ISSUE TITLE
some services/sensors are missing

### ISSUE THREAD

**Issue by dbaron92** [vaparr/ha-overseerr#21]
I installed it and I can see two sensors such as
sensor.overseerr_issues
sensor.overseerr_pending_request

I dont see the rest such as movie request, tv request, etc.. 

The error log:
2022-09-02 20:54:31.650 ERROR (MainThread) [homeassistant.components.sensor] overseerr: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/overseerr/sensor.py", line 82, in update
self._state = self._overseerr.movie_requests
File "/usr/local/lib/python3.10/site-packages/pyoverseerr.py", line 241, in movie_requests
requests = self._request_connection(f"Request/count").json()["movie"]
KeyError: 'movie'
2022-09-02 20:54:32.082 ERROR (MainThread) [homeassistant.components.sensor] overseerr: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/overseerr/sensor.py", line 88, in update
self._state = self._overseerr.tv_requests
File "/usr/local/lib/python3.10/site-packages/pyoverseerr.py", line 263, in tv_requests
requests = self._request_connection(f"Request/count").json()["tv"]
KeyError: 'tv'
2022-09-02 20:54:32.242 ERROR (MainThread) [homeassistant.components.sensor] overseerr: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/overseerr/sensor.py", line 85, in update
self._state = self._overseerr.total_requests
File "/usr/local/lib/python3.10/site-packages/pyoverseerr.py", line 275, in total_requests
requests = self._request_connection(f"Request/count").json()["total"]
KeyError: 'total'

Another error log:
Logger: homeassistant.helpers.entity_component
Source: helpers/entity_component.py:47
First occurred: 9:04:30 PM (3 occurrences)
Last logged: 9:04:31 PM

Forced update failed. Entity sensor.overseerr_movie_requests not found.
Forced update failed. Entity sensor.overseerr_tv_show_requests not found.
Forced update failed. Entity sensor.overseerr_total_requests not found.

Did I miss anything another than configuration.yaml (it is similar to your "full example" except api and ip address info)? Thanks :)

**Comment by vaparr** [comment]
That is really strange.  Are the issue sensors reporting any data. or just 0?

If i had to guess, the api key might be incorrect, or we may be failing to connect.  No other errors during startup?

**Comment by dbaron92** [comment]
Both sensors are reporting 0
sensor.overseerr_issues
sensor.overseerr_pending_request

I replaced with new api and new sensors didnt showed up after uninstalled/installed. I dont see any errors in logs as well.

**Comment by dbaron92** [comment]
Its working now with Overseerr's stable version 1.30. Im not sure why old version didnt work for me.
