### ISSUE TITLE
[Feature Request] Have a property to know if request is in 4K or not

### ISSUE THREAD

**Issue by hbooo** [vaparr/ha-overseerr#4]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to know if a request is done in 4K or not. 

**Describe the solution you'd like**
Add a property in sensor.overseerr_pending_requests in order to be able to display the fact that a request is done for a 4K version.

**Comment by vaparr** [comment]
just added this.  Should be fixed in 0.1.23

**Comment by hbooo** [comment]
Hi, just updated but I have this error now in the logs

Logger: homeassistant.helpers.entity
Source: custom_components/overseerr/sensor.py:83
First occurred: 20:26:25 (9 occurrences)
Last logged: 20:34:25

Update for sensor.overseerr_pending_requests fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/sensor.py", line 83, in update
    self._last_request = self._overseerr.last_pending_request
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 284, in last_pending_request
    return self.create_request_object(request)
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 123, in create_request_object
    "last_request_status": request["status4k"],
KeyError: 'status4k'

**Comment by vaparr** [comment]
Looks like your overseerr might be behind? Can you try updating to the develop branch?

**Comment by hbooo** [comment]
Sorry forgot to say that I'm with version develop-6c437c515fc01b9fe4461968875e23542bae7542

If I access local ip of api v1 request I got nothing (I only access Overseerr by dns) but If I connect on local ip I have content.

My current config for running HA and Overseerr is by docker on Unraid

**Comment by hbooo** [comment]
Fixed with last version thanks
