### ISSUE TITLE
Forced update failed & NoneType errors

### ISSUE THREAD

**Issue by ZuluWhiskey** [vaparr/ha-overseerr#6]
Not sure when they started showing but I’m currently getting the following in my HA logs:

```
2021-07-12 14:59:05 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.overseerr_movie_requests not found.
2021-07-12 14:59:05 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.overseerr_total_requests not found.
2021-07-12 15:00:05 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.overseerr_movie_requests not found.
2021-07-12 15:00:05 WARNING (MainThread) [homeassistant.helpers.entity_component] Forced update failed. Entity sensor.overseerr_total_requests not found.
```

I believe it’s to do with these errors which I get when HA starts up:
```
2021-07-12 14:58:15 ERROR (MainThread) [homeassistant.components.sensor] overseerr: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/sensor.py", line 71, in update
    self._last_request = self._overseerr.last_movie_request
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 241, in last_movie_request
    return self.create_request_object(request)
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 145, in create_request_object
    "last_request_poster": self.get_poster_url(movie_data["posterPath"]),
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 103, in get_poster_url
    return ("https://image.tmdb.org/t/p/w600_and_h900_bestv2" + path)
TypeError: can only concatenate str (not "NoneType") to str
2021-07-12 14:58:16 ERROR (MainThread) [homeassistant.components.sensor] overseerr: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/sensor.py", line 74, in update
    self._last_request = self._overseerr.last_total_request
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 291, in last_total_request
    return self.create_request_object(request)
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 145, in create_request_object
    "last_request_poster": self.get_poster_url(movie_data["posterPath"]),
  File "/usr/local/lib/python3.8/site-packages/pyoverseerr.py", line 103, in get_poster_url
    return ("https://image.tmdb.org/t/p/w600_and_h900_bestv2" + path)
TypeError: can only concatenate str (not "NoneType") to str
```

HA version: 2021.6.6
ha-overseerr version: 0.1.29
Overseerr version: 57b52fc9cccd3fac93cdb68e36cf652ddbcdf86c (it’s “Up to Date” according to the UI)

I’ve not changed anything in Overseerr recently apart from updating my Docker image

**Comment by vaparr** [comment]
This should be fixed
